#!/bin/bash
# Deploy the Python app to shinyapps.io
# NOTE: not for external users!

# Steps to deploy:
# 1. Archive existing app
# 2. Delete existing app
# 3. Run this script

cd binomialbias
rm -rf rsconnect-python
rsconnect deploy shiny . --name sciris --title "binomialbias"
