#!/bin/bash
# Can supply additional arguments, e.g. ./start_server --debug
voila Antidiscrimination.ipynb --port=8867 --no-browser --show_tracebacks=True --MappingKernelManager.cull_interval=120 --MappingKernelManager.cull_idle_timeout=600 "$@"
